### ISSUE TITLE
翻译脚本的一些小bug

### ISSUE THREAD

**Issue by TaQini** [dragove/dotfiles#1]
一些特殊符号会被crow当作解析，比如`-` , `)` 
基本上文本中带`-`的都翻译不了，改成`"$(wl-paste -p)"`会好一些
```bash
transout=$(crow -t zh-CN "$(wl-paste -p)" -b)
notify-send "$transout"
```
不过像是`-h` 这样的参数 还是会被直接解析

**Comment by dragove** [comment]
已经修复 https://github.com/dragove/dotfiles/commit/2e5fd343150d64f961ffe2e307fc7c8a24cf189f#diff-f23b70da8abe4d4ed2131c885a4e6da536b1fbe0654630875294e636ef8f47a7
使用如下脚本能避免各种问题
```bash
transout=$(crow -b -t zh-CN -- "$(wl-paste -p)")
notify-send -- "$transout"
```
